export const GET_MOVIE_DETAILS_RECOMMEND = 'GET_MOVIE_DETAILS_RECOMMEND';
export const GET_MOVIE_DETAILS_RECOMMEND_SUCCESS =
  'GET_MOVIE_DETAILS_RECOMMEND_SUCCESS';
export const GET_MOVIE_DETAILS_RECOMMEND_ERROR =
  'GET_MOVIE_DETAILS_RECOMMEND_ERROR';
