export const GET_TRENDING_WEEK_MOVIE = 'GET_TRENDING_WEEK_MOVIE';
export const GET_TRENDING_WEEK_MOVIE_SUCCESS =
  'GET_TRENDING_WEEK_MOVIE_SUCCESS';
export const GET_TRENDING_WEEK_MOVIE_ERROR = 'GET_TRENDING_WEEK_MOVIE_ERROR';
