export const GET_ANIMATION_MOVIE = 'GET_ANIMATION_MOVIE';
export const GET_ANIMATION_MOVIE_SUCCESS = 'GET_ANIMATION_MOVIE_SUCCESS';
export const GET_ANIMATION_MOVIE_ERROR = 'GET_ANIMATION_MOVIE_ERROR';
